INDIRECTION_COLUMN = 0
RID_COLUMN = 1
TIMESTAMP_COLUMN = 2
SCHEMA_ENCODING_COLUMN = 3
PRIMARY_KEY_COLUMN = 4

ARRAY_SIZE = 4096
VALUE_SIZE = 8
PAGE_RANGE_SIZE = 16

BASE_PAGE = 0
TAIL_PAGE = 1
BUFFERPOOL_MAX_LENGTH = 18 #increase later