INDIRECTION_COLUMN = 0
RID_COLUMN = 1
TIMESTAMP_COLUMN = 2
SCHEMA_ENCODING_COLUMN = 3
BASE_ID_COLUMN = 4
PRIMARY_KEY_COLUMN = 5

BASE_PAGE = 0
TAIL_PAGE = 1
PAGE_RANGE_SIZE = 16

# page range size is array/value
ARRAY_SIZE = 4096
VALUE_SIZE = 8

# experiment with these
BUFFERPOOL_MAX_LENGTH = 1024 #increase later
UPDATES_BEFORE_MERGE = 512
